// lib/application/providers/global/loading/state/loading_state.freezed.dart
// This file will be generated by build_runner.
// For now, create an empty file or a file with minimal content
// to avoid analysis errors if other files import it.
// Example minimal content:
part of 'loading_state.dart';
// // Add freezed generated code placeholder if necessary, or leave empty.
// // The actual content will be filled by build_runner.
