name: start_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # 状態管理
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # 画面遷移
  go_router: ^13.2.4

  # 画像/SVG
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  # UI/UX
  animations: ^2.0.11

  # その他必須
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  
  # コード生成
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
