// lib/application/providers/global/theme/state/theme_state.freezed.dart
// This file will be generated by build_runner.
// Create an empty file or a file with minimal content.
part of 'theme_state.dart';
