// lib/application/providers/global/app_layout/state/app_layout_state.freezed.dart
// This file will be generated by build_runner.
// Create an empty file or a file with minimal content.
part of 'app_layout_state.dart';
